# Generated by Django 5.0.3 on 2024-03-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Applicant_Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=10)),
                ('Ownership', models.CharField(max_length=100)),
                ('GovtID_Type', models.CharField(max_length=100)),
                ('ID_Number', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Load_Applied', models.IntegerField()),
                ('Date_of_Application', models.DateField()),
                ('Date_of_Approval', models.DateField(blank=True, null=True)),
                ('Modified_Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('Reviewer_ID', models.IntegerField()),
                ('Reviewer_Name', models.CharField(max_length=100)),
                ('Reviewer_Comments', models.TextField()),
            ],
        ),
    ]
