# Generated by Django 5.0.3 on 2024-03-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Date_of_Application',
            field=models.DateField(verbose_name='%d-%m-%Y'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Date_of_Approval',
            field=models.DateField(blank=True, null=True, verbose_name='%d-%m-%Y'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Modified_Date',
            field=models.DateField(verbose_name='%d-%m-%Y'),
        ),
    ]
